version: "2"

services:
  mongo:
    container_name: local_mongo
    image: mongo
    ports:
      - 27017:27017

  redis:
    container_name: local_redis
    image: redis
    ports:
      - 6379:6379

  postgres:
    container_name: local_postgres
    image: postgres:11.5
    ports:
      - 5432:5432
